### PR TITLE
Skip unconditionally on the follower

### PR DESCRIPTION
**Pull request by daniel-grumberg**
OK, this implements the the first proposed fix on the basic asan support issue. The syntax is detailed in the `test/passing/skip_multiple.div` test case. The way this meshes with the rest of the language, is that it first tries to match the follower's system call with the current sequence. If it fails to match then, it will check if the system call should be skipped, if yes it will return `SKIP`, if not it will diverge as usual.

### CODE REVIEW

**Comment by luisggpina** [comment]
Looks good.  I guess this is extensible to support conditional skips in a future PR.  I'll review and merge this later today.

**Comment by daniel-grumberg** [comment]
This supports conditional skips if and only if you can express the conditions in a code block using only the arguments and syscall number of the system call to be skipped.

**Comment by luisggpina** [comment]
That's fine.  But the current code already has support for such code blocks?  If so, could you add a test that shows that usage?

**Comment by daniel-grumberg** [comment]
Ok, I added the test under the name `skip_cond` and as I imagined it worked just fine. I will wait for you to review this, and then I will merge all 2 test commits before you can merge it in the master branch.
N.B. Sorry this took a while I was very busy trying to find someone to supervise my 3rd year group project, but it is all good now.

**Comment by luisggpina** [comment]
Ok, looks good!  Thanks for adding the extra test.  I've taken a look at the rest of the code and I'm happy with it.  Feel free to merge the 2 commits, let me know when you have so I can merge this PR.

I'm glad you found a supervisor for your group project.  The start of the semester is always stressful.

**Comment by daniel-grumberg** [comment]
Done

**Pull request merged**
